In [14]:
import tensorflow as tf
import numpy as np

In [3]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [10]:
c = tf.multiply(a, b)

In [11]:
with tf.Session() as sess:
    print sess.run(c, feed_dict={a: [1,3], b: [2, 4]})

[  2.  12.]


In [26]:
x = tf.placeholder(tf.float32, [3, 3])
d = tf.add(x, x)

In [27]:
np.random.seed(1)
with tf.Session() as sess:
    print sess.run(d, feed_dict={x: np.random.rand(3,3)})

[[  8.34043980e-01   1.44064903e+00   2.28749632e-04]
 [  6.04665160e-01   2.93511778e-01   1.84677184e-01]
 [  3.72520417e-01   6.91121459e-01   7.93534935e-01]]


## Simple Linear Model

In [59]:
X = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
W = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [60]:
y_ = W * X + b

In [61]:
squared_error = tf.square(y_ - y)
loss = tf.reduce_sum(squared_error)
init = tf.global_variables_initializer()

In [63]:
with tf.Session() as sess:
    sess.run(init)
    print sess.run(loss, feed_dict={X: [1, 2, 3], y: [0, 1, 2], W: 0.3, b: -0.3})
    print sess.run(loss, feed_dict={X: [1, 2, 3], y: [0, 1, 2], W: 1, b: -1})

2.45
0.0
